### ISSUE TITLE
YouTube embeds size is not responsive

### ISSUE THREAD

**Issue by olayway** [life-itself/community#816]
Small screens:

![image](https://github.com/life-itself/community/assets/52197250/0a6dc149-56b9-490f-8574-effa40e40768)

Medium/large screens:

<img width="1582" alt="image" src="https://github.com/life-itself/community/assets/52197250/5ad59b07-4427-4ab9-a889-8ed99efe52c2">

**Comment by Sky-De** [comment]
@olayway hi there, i would like to work on this issue, please assign this to me, as soon as i get assignment i will start working on this 
thanks

**Comment by olayway** [comment]
@Sky-De That's great! 🙌 Thank you!

**Comment by Sky-De** [comment]
@olayway hi again, i ran into error as soon as i start project to run

## Screenshot
![1](https://github.com/life-itself/community/assets/79264045/f114cde7-6c78-49e7-8451-e2081279d4d8)

it has something to do with **.contentlayer** and it's first time i see this type of code with this approach

please share with me any solution to run this app successfully
this is my only main problem now  however there is another problem which i will mention below 

## another thing

I think you should do something for volume of your app because it is the first time ever that i clone repository with this amount of volume
![Untitled](https://github.com/life-itself/community/assets/79264045/7eeeb107-c60c-48a6-a9b6-f534dbd9d9be)

**Comment by Sky-De** [comment]
@olayway hi again, it has been 3days which i'm wating for your response for my issues dealing with this project , it seeems you are not really serious about this projecet, so i have to unassign myself of this issue, have luck
thanks for understanding

**Comment by olayway** [comment]
@Sky-De Np, I'll fix it myself.
